source 'git@bitbucket.org:vnac/podsrepo.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'GeometryUtilities-iOS' do

	platform :ios, '8.0'

	use_frameworks!

	pod 'GeometryUtilities', :path => '../'
	pod 'Nimble', '~> 5.0'

end

target 'GeometryUtilities-macOS' do

	platform :osx, '10.10'

	use_frameworks!

	pod 'GeometryUtilities', :path => '../'
	pod 'Nimble', '~> 5.0'

end
